repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.25.1
    hooks:
      - id: check-plists
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.moojomoore."]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
